[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm start"

[[redirects]]
  from = "/docs"
  to = "https://github.com/houseocloth/sewem-ipsum#readme"
  status = 301

[[edge_functions]]
  path = "/api/v0/*"
  function = "api"
