name = "sewem-ipsum"
main = "worker/index.ts"
compatibility_date = "2023-04-21"

rules = [
  { type = "Data", globs = ["**/*.png"], fallthrough = true },
]

[build]
  command = "npm run build"

[vars]
  DOCS_URL = "https://github.com/houseofcloth/sewem-ipsum"
